### PR TITLE
src/liboping.c: Performance improvements.

### PR DESCRIPTION
**Pull request by octo**
Taken from: http://mailman.verplant.org/pipermail/collectd/2011-July/004640.html

Luke Heberling collectd at c-ware.com wrote:

> I'm finding collectd's ping plugin inadequate for host lists larger than
> a few hundred. It consumes an entire 2.8Ghz CPU and reports random false
> packet loss (Latest collectd and liboping from git.verplant.org on
> debian squeeze and lenny). This seems to be because of some
> inefficiencies in liboping. For instance, a FD is created for every
> host. Since each raw socket receives all raw packets, only one FD would
> be needed for all hosts (of the same addrfamily). Besides consuming all
> those additional FD's, each reply packet is received and processed
> separately on each FD causing O(n^2) complexity. Also for each packet
> processed on each FD, a scan of all hosts is performed causing O(n^3).
> 
> So, I implemented some new features for liboping:
> - use icmp ident as "hash" for table lookup on RX
> - allocate one socket FD per addressfamily (not per host)
> - multiplex socket writes in the same select loop as reads
>   - This was necessary because sometimes the first reply
>      is received before last request is sent.
> 
> It's working well for me in testing so far. 1-3% CPU with 1000 hosts,
> compared to 100% and useless at 500 hosts before these changes. If
> there's interest I'll update this thread with any significant changes.
> As always, changes to address style/portability/other issues that
> inhibit integration upstream will be my pleasure.

### CODE REVIEW

**Comment by vincentbernat** [comment]
I am using this patch for our monitoring system and it works fine. We needed it as we reached the limit of what liboping was able to handle around 300 hosts. I didn't get through the trouble to rebase it against master.

**Comment by octo** [comment]
So, I finally got around to tackling this merge conflict from hell. Any feedback from users who actually use liboping at this scale would be very welcome :)

**Comment by octo** [comment]
ping @hanynowsky, @vincentbernat: this is ready for testing; any feedback would be very welcome!

**Comment by vincentbernat** [comment]
I'll be able to test that later this month. Thanks!

**Comment by hanynowsky** [comment]
I ll give it a shot in few days! Thanks for the hard work @octo

**Pull request merged**
